export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

export const LOAD_COURSES = "LOAD_COURSES";
export const GET_COURSE = "GET_COURSE";
export const EDIT_COURSE = "EDIT_COURSE";
export const REMOVE_COURSE = "REMOVE_COURSE";

export const LOAD_SERVICE_PROVIDERS = "LOAD_SERVICE_PROVIDERS";
export const GET_SERVICE_PROVIDER = "GET_SERVICE_PROVIDER";
export const REMOVE_SERVICE_PROVIDER = "REMOVE_SERVICE_PROVIDER";

export const LOAD_USERS = "LOAD_USERS";
export const LOAD_LEARNERS = "LOAD_LEARNERS";
export const ADD_MENTOR = "ADD_MENTOR";
export const ADD_TUTOR = "ADD_TUTOR";
